@echo off
cls
REM  make32.bat -  Batch file for assembling/linking 32-bit Assembly programs

REM Add the -Sg command line option (displays generated code generated by MASM)

REM The following three lines can be customized for your system:
REM ********************************************BEGIN customize
SET PATH=%cd%
SET INCLUDE=%cd%\include
SET LIB=%cd%\lib
REM ********************************************END customize


REM /nologo: Suppresses the display of the startup banner and copyright message.
REM -Zi: Generates debugging information.
REM -c: Assembles the source file without linking.
REM -Fl: Generates a listing file.
REM -coff: Specifies the output format as Common Object File Format (COFF).

ML /nologo -c -Fl -coff src\%1.asm
if errorLevel 1 goto terminate


REM add the /MAP option for a map file in the link command.

LINK32 /nologo %1.obj irvine32.lib kernel32.lib /SUBSYSTEM:CONSOLE /DEBUG
if errorLevel 1 goto terminate

REM dir %1.*

REM run the executable file
%1.exe

:terminate
